### PR TITLE
Unify H-Bar End STLs

### PR DESCRIPTION
**Pull request by kieraneglin**
## Summary

This PR removes the `1-HbarEndRight` STL and renames `1-HbarEndLeft` to simply `2-HbarEnd`.

## Notes

The D-Bot designs calls for different H-Bar ends since one end must accept hardware for the Y-endstop bumper (see pic below). Since that doesn't apply to the sand table, that STL can be removed and the left/right designs merged into one.

This isn't a hugely consequential change, but I believe it will make building the gantry slightly clearer. If there's interest in this PR, I'll push up some similar changes to unify the print carriage STLs as well!

## Screenshots

Screen Shot 2023-01-22 at 3 20 04 PM

### CODE REVIEW

**Comment by kieraneglin** [comment]
Hey @rdudhagra , just checking if there are any interest for these style of PRs. If so, I have a few more changes ready to go that I'd love to share!

**Comment by rdudhagra** [comment]
Hey @kieraneglin , thanks for the PRs! These are all great changes—just had a bunch of other things I need to get through so apologies for the delay. 

Let me make sure the Fusion360 model is updated to reflect this change and then I'll merge.

**Comment by kieraneglin** [comment]
Thank you very much! Since I have at least two more changes ready to go (simplification of the magnet carriage and a simplification of the rear idlers), would you like me to make PRs for those changes so you can make all necessary F360 updates at the same time?

**Comment by rdudhagra** [comment]
Yea that would help—thanks!

**Comment by kieraneglin** [comment]
@rdudhagra I've created PRs for all the parts I've modified! Thank you for your time and your work on this project. 

If you would like, I can eventually create another PR with some README changes (if necessary) once I know what PRs have/haven't been accepted.

**Comment by rdudhagra** [comment]
Thanks @kieraneglin! Actually if you have F3D/step/some other file format I can convert that would be really helpful!

**Comment by kieraneglin** [comment]
@rdudhagra if you're interested in merging some of these PRs, I started paying for Fusion 360 professional and it includes a _really_ good mesh converter. Once I know what files you want to include, I can create a PR with very nice STEP files for each model if it would help

No pressure - just thought I'd offer!

**Comment by rdudhagra** [comment]
Hi @kieraneglin, so sorry for not getting to this earlier. All these suggestions are fantastic and I'll definitely integrate them. I'm just swamped with classes/etc so I'll get to this in mid-May after I graduate.

**Comment by kieraneglin** [comment]
@rdudhagra no problem at all! Schooling certainly comes first. 

My table is actually mostly done, but I'm not happy with how loud it is. I want it to be as unintrusive as possible during operation. I've been running a lot of tests with different stepper motors, dampers, decoupling mechanisms, ball sizes, magnet clearance, the surface the sand rests on, among other things. I've collected some really good information and, if you're interested, I could contribute that information in a markdown document to add to this repository. 

Again, that can wait! I still have a few more tests to run so I'm not in any rush either.

**Comment by jangrewe** [comment]
Hi @rdudhagra and @kieraneglin, i'm currently in the design process for my table (as in: the wood parts) and have ordered pretty much all of the other hardware, so i could start printing the parts anytime now.

Any chance we can get all these PRs merged? I was close to start redesigning some of the models to streamline things, but these PRs do a lot of the heavy lifting already. 😉

**Comment by rdudhagra** [comment]
Apologies for the delay...PRs are merged in.

**Pull request merged**
